= Three short Emacs tips for Windows
:hp-tags: Emacs, MindTheGap, ShortTips

== Set proxy

If you want to use MELPA, ELPA, etc. you need to configure the proxy in the init file:

[source,elisp]
----
(setq url-proxy-services
   '(("no_proxy" . "^\\(localhost\\|10.*\\)")
     ("http" . "172.21.131.234:8080")
     ("https" . "172.21.131.234:8080")))
----

== UTF-8

Being a native Spanish speaker, sometimes I drop accented characters, like the á in Sebastián

[source,elisp]
----
(prefer-coding-system 'utf-8)
----

The problem seemed to be that the defauls in Emacs and in Windows are different. Whatever the case, this solved all my encoding problems.

== Dired-launch

I still deal daily with Excel, Word, Outlook, etc. I did replace almost 100% of the Windows Explorer with Dired, and one of the small tools that made a difference for me was dired-launch: https://github.com/thomp/dired-launch
Basically what dired-launch does is equivalent to `start "" file-path` in the command prompt.

I have it bound to J (shift + j) and C-c j, although I think J is the default binding, and for some reason I added an extra one. For Windows there isn't any other configuration required:

[source, elisp]
----
(dired-launch-enable)
(global-set-key (kbd "\C-cj") 'dired-jump)
----

