= Three short Emacs tips for Windows
:hp-tags: Emacs, MindTheGap, ShortTips

Three small tips for your `init.el` file.

== Set proxy

If you want to use MELPA, ELPA, etc. behind your corporate proxy, you need to configure it in the init file:

[source,elisp]
----
(setq url-proxy-services
   '(("no_proxy" . "^\\(localhost\\|10.*\\)")
     ("http" . "10.10.10.10:8080")
     ("https" . "10.10.10.10:8080")))
----

A good way to get your proxy (unless the admins are cool and just share it) is to get the .dat file, as explained here: https://superuser.com/questions/346372/how-do-i-know-what-proxy-server-im-using

I would also recommended to set the proxy in HTTP_PROXY and HTTPS_PROXY.

== UTF-8

Being a native Spanish speaker, sometimes I drop accented characters, like the á in Sebastián

[source,elisp]
----
(prefer-coding-system 'utf-8)
----

The problem seemed to be that the defauls in Emacs and in Windows are different...or something like that. Whatever the case, this single line solved all my encoding problems.

== Dired-launch

I still deal daily with Excel, Word, Outlook, etc. I did replace 99% of  Windows Explorer with Dired, and one of the small tools that made a difference for me was dired-launch: https://github.com/thomp/dired-launch
Basically what dired-launch does is equivalent to `start "" file-path` in the command prompt.

I have it bound to J (shift + j) and C-c j, although I think J is the default binding, and for some reason I added an extra one that I'm not using?.
Anyway, for Windows there isn't any other configuration required:

[source, elisp]
----
(dired-launch-enable)
(global-set-key (kbd "\C-cj") 'dired-jump)
----

Now you can launch any type of file from the Dired buffer directly.