= First tip: find your %HOME%
:hp-tags: MindTheGap, ConfigurationTips

I remember when I first started using Python at work (for personal use tools, nothing I could share with anyone _*cofcof*at least officially*cofcof*_) I quickly found out that I needed to configure some environment variables for things to work smoothly.
This felt, at a time, like a stylistic choice from the Python folks to get some configuration done in the simplest way possible while making it cross platform. I can see how implementing registry stuff for Windows is a pain, I also stay away from it as much as I can.

However, when I started using more and more tools that depended on environment variables, I realized that there's a lot more than just %PATH% in life.
By the time I moved to Linux at home I was already more than comfortable with the idea that something depended on an environment variable.

== %HOME% is where the bin is

So if you are taking in the journey to master Python, Emacs, Vim, etc. I strongly suggest you select one folder in your hard drive and set it to the %HOME%. For Emacs for example, this determines where your config files will live. By default Emacs will do the right thing and put it in your %USERPROFILE% (C:\Users\<username>, but in older versions of Windows it was "Documents and Settings").
In my case I used "C:\HomeFolder\" which honeslty sounds quite dumb. But you know, cache invalidation and naming things, right? (that's one quote worth keeping in mind when starting a new project. And naming folders).

That's where I keep the config for all my tools. Python packages 99% of the time will drop the "dot directories" in there, Emacs as mentioned does the same. The reason for this is that in Linux/Unix, each user in the computer gets their own directory in /home/username, where all the "stuff" (not only config but documents, etc.) will live. In a way, it's a combination of (some) registry settings and %USERPROFILE%

There's one more thing I've added to my PATH which is related to my home folder, which we usually don't have in Windows but can come in quite handy, and that is a bin folder. Usually in Linux there's a bin directory that contains the binaries (or, executables) for your tools. In Windows everything is spread out in the two Program Files folders, but if you start using more command line tools you'll quickly realize it's better to drop them all in one place.

So since these are things I call mostly from the command line I place my magic folder in C:\HomeFolder\cmdbin and for example that's where I dropped the excellent GnuWin32 utilities (Windows versions of grep, find, etc.)

By the way, the reason I didn't just install Cygwin, is that I want to stay as much as possible in the "native" Windows world, so I can combine these tools with my older Win32 workflows as much as needed.


== Dude where's my binaries folder?

One thing to notice, your user profile in many companies is setup in a way that you can login in different computers and have all your settings available.
I've never quite liked this feature, honestly. It depends (as many things in Windows do) on the app developers playing nicely and doing things The Right Way (which we rarely do...). So if you rely on the profile, you'll be dissappointed sooner or later, and on top of that your first login on a different computer can take a while to sync all your stuff.

With the Home folder approach, it's definitely up to you to every once in a while to sync your folder between different computers or keep a back in case your hard drive dies. That's the reason I put my bin inside the home folder. Every once in a while (usually when I configured something new and it took me a while) I zip the entire thing and keep that copy somewhere else.
It happens rarely enough that it isn't a huge pain, and at the same time if I have to move computers (which has already happened) getting my carefully created config back up again it's really straightforward.

== There's more

I also recommended looking around the interwebs for PYTHONPATH, PYTHON, HTTP_PROXY and HTTPS_PROXY. These are as well documented as %HOME%, but unlike the later they are much less opinionated.

